Doctrine\Tests\ORM\Mapping\GenderType:
 type: entity
 repositoryClass: Doctrine\Tests\ORM\Mapping\GenderTypeRepository
 table: gender_type
 schema: users_records
 indexes:
   name_index:
      columns: [name]
 id: 
  id:
    type: integer
    generator:
      strategy: AUTO 
 fields:
  gender_type_name:
    type: text
    length: 50
lifecycleCallbacks:
    prePersist: [ doStuffOnPrePersist, doOtherStuffOnPrePersistToo ]
    postPersist: [ doStuffOnPostPersist ]