Doctrine\Tests\ORM\Mapping\PhoneNumber:
 type: entity
 repositoryClass: Doctrine\Tests\ORM\Mapping\PhoneNumberRepository
 table: Phone_number
 schema: users_records
 indexes:
   name_index:
      columns: [name]
 id: 
  id:
    type: integer
    generator:
      strategy: AUTO 
 fields:
  phonenumber:
    type: integer
    length: 50
lifecycleCallbacks:
    prePersist: [ doStuffOnPrePersist, doOtherStuffOnPrePersistToo ]
    postPersist: [ doStuffOnPostPersist ]